# Generated by Django 4.2.5 on 2024-08-03 20:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_apis", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="descripton",
            new_name="description",
        ),
    ]
